CONFIG = {
    'FACEBOOK_TOKEN': 'EAAEg9PWjtr8BAMfEftZCWXPcNM1wI1xYEUipwZBZB42loKX0Jg12XTEVYFTRIayaVZAMjFepPXAhGZAW4yAAZAfJcgVIfUvFIUDtmE68QzTZA6tP5LxLUvGSP4M58R5F5ZBB6Pt8LU3ZB29tgk8EPV4KymFV1ZCu9kOxubyhTCUJm3sQZDZD',
    'VERIFY_TOKEN': 'verify_simsimbot',
    'SERVER_URL': 'https://karl.llisten.me'
}